FROM ubuntu:16.04

WORKDIR /usr/local/src

# jdk的包必须已下载好
ADD jdk-8u181-linux-x64.tar.gz /usr/local/src

ENV JAVA_HOME /usr/local/src/jdk1.8.0_181
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $PATH:$JAVA_HOME/bin