version: '2.3'
services:
  spring-boot-pay:
    image: hrxz/spring-boot-pay:0.0.1
    container_name: spring-boot-pay
    ports:
      - "80:8080"
    volumes:
      - /data/img:/data/img
    environment:
      - SERVER_PORT=8080
      - REDIS_HOST=localhost
      - REDIS_PORT=6380
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3307
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=SATYmmMvf8tH
      - ADMIN_USER_ID=1
      - FILE_PATH=/data/img
      - FILE_URL_PREFIX=/file/
      - JAVA_OPTIONS=-XX:CompressedClassSpaceSize=32m