server:
  port: ${SERVER_PORT:8080}

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
  redis:
    database: 0 # 使用0号库
    host: ${REDIS_HOST:111.230.157.97}
    port: ${REDIS_PORT:6380} # Redis服务端口
    password: # 服务器连接密码(默认为空)
    pool:
      max-idle: 100 # 池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
      min-idle: 0 # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
      max-active: 8 # 池在给定时间可以分配的最大连接数。使用负值无限制。
      max-wait: -1 # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
    ssl: false # 启用SSL支持
    timeout: 0 # 以毫秒为单位的连接超时。
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:111.230.157.97}:${MYSQL_PORT:3306}/hrzx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:SATYmmMvf8tH}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

super-admin:
  user-id: ${ADMIN_USER_ID:1}